name: CI for Angular
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 18.20.4
      - name: Install dependencies
        run: npm i
      - name: run tests
        run: ng test --no-watch --code-coverage --browsers=ChromeHeadlessCI
